### ISSUE TITLE
Make work on Windows

### ISSUE THREAD

**Issue by hashrock** [3100/trahald#6]
元々、Windowsで動作していたこと自体が奇跡のようなものですが、Windowsユーザに一杯の冷えた水をプレゼントするのもいいでしょう :-)

gritはUNIX環境に依存しており、Windowsではrequireした時点でエラー終了します。回避策としては、下記の二つがあるでしょうか。
- Windows上ではgritを外せるようにする（プラグイン化）
- gritからRuggedへ移行する

特に前者を適用すると、Git連携するWikiというコンセプトは弱まりますが、その代わりにJRuby上での動作も見込めるかもしれません。

**Comment by 3100** [comment]
https://github.com/github/gollum/issues/356

Ruggedはより低レベルのラッパーらしいですが、やってみる価値はあるかもしれないですね。
次回LNまでにちょっとRugged触っておきます。

ついでに言うと、mojombo作のツールは大抵1.8対応のツケでutf8周りがひどいので、Ruggedが1.9寄りだといいなぁ。

**Comment by hashrock** [comment]
rackup -E "redis" で動作するようになりました！
gitにこだわらなければCloseでもいいような気がします。

**Comment by 3100** [comment]
[http://trahald.iplwiki.info/JRuby対応への道](http://trahald.iplwiki.info/JRuby対応への道)

結局gritが関わっているので、もう少し様子を見てみます。

**Comment by 3100** [comment]
JRuby1.7.3の問題も #10 で治ったようなので、一旦クローズします。
